"""empty message

Revision ID: 834c45d6aba2
Revises: 
Create Date: 2024-09-20 23:58:39.191339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834c45d6aba2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
